src/Entity/Commercial.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommercialRepository")
 */
class Commercial
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     *
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $function_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $c_key;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     *
     */
    private $password;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getFunctionName(): ?string
    {
        return $this->function_name;
    }

    public function setFunctionName(string $function_name): self
    {
        $this->function_name = $function_name;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCKey(): ?string
    {
        return $this->c_key;
    }

    public function setCKey(string $c_key): self
    {
        $this->c_key = $c_key;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = $password;
    }


}

src/Controller/CommercialManagerController.php
<?php

namespace App\Controller;

use App\Entity\Commercial;
use App\Form\CommercialEditType;
use App\Form\CommercialRegistrationType;
use App\FormEntities\CommercialFormEntity;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


class CommercialManagerController extends AbstractController
{
    /**
     * @Route("/admin/clist", name="commercials_list")
     */
    public function index() : Response
    {
        $doctrine = $this->getDoctrine()->getManager();
        $commercials = $doctrine->getRepository(Commercial::class)->findAll();
        return $this->render('commercial_manager/list.html.twig', [
            'commercials' => $commercials
        ]);
    }

    /**
     * @Route("/admin/remove/{id}", name="commercials_remove")
     */
    public function delete($id) : Response
    {
        $doctrine = $this->getDoctrine()->getManager();
        $commercial = $doctrine->getRepository(Commercial::class)->find($id);
        $doctrine->remove($commercial);
        $doctrine->flush();
        return $this->redirectToRoute('commercials_list');
    }

    /**
     * @Route("/admin/register", name="registration")
     */
    public function registration(Request $request, ObjectManager $em, UserPasswordEncoderInterface $encoder)
    {
        $commercialForm = new CommercialFormEntity();
        $form = $this->createForm(CommercialRegistrationType::class, $commercialForm);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $commercial = $commercialForm->getCommercial();
            $user = $commercial->getUser();
            $hash = $encoder->encodePassword($user,$user->getPassword());
            $user->setPassword($hash);
            $commercial->setUser($user);
            $em->persist($commercial);
            $em->flush();
            return $this->redirectToRoute('commercials_list');
        }
        return $this->render('admin/registration.html.twig',array('form'=>$form->createView()));
    }

}

templates/commercial_manager/edit.html.twig
{% extends 'admin/baseadmin.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<div class="container">
    <h1>Inscription</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-success">Inscription</button>
    {{ form_end(form) }}
</div>

    <script>
        $(document).ready(function() {
            var url = "{{ path('comemrcial_data') }}";
            var mapper = {
                'CO_Nom' : 'commercial_registration_lastname',
                'CO_Prenom' : 'commercial_registration_firstname',
                'CO_Fonction' : 'commercial_registration_function_name',
                'CO_Ville' : 'commercial_registration_city',
                'CO_Telephone' : 'commercial_registration_phone',
                'CO_EMail' : 'commercial_registration_email'
            };
            $('#commercial_registration_c_key').change(function (e) {

                var value = this.value;
                $.ajax({
                    type: "GET",
                    url: url,
                    dataType: "json",
                    data: {'reference' : value},
                    success: function(data) {
                        var realData = data.data;
                        $.each(mapper, function(i, val) {
                            $("#" + val).val(realData[i]);
                        });
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/commercial_manager/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'src/Controller/CommercialManagerController.php'|file_link(0) }}">src/Controller/CommercialManagerController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'templates/commercial_manager/index.html.twig'|file_link(0) }}">templates/commercial_manager/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/commercial_manager/list.html.twig
{% extends 'admin/baseadmin.html.twig' %}
{% block title %}Liste des commerciaux{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('datatables') }}
{% endblock stylesheets %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('datatables') }}
{% endblock javascripts %}
{% block body %}
    {{ parent() }}
    <div class="container">

        <div class="col-md-12">
        <h2>Liste des commerciaux</h2>
        <table id="example" class="table table-striped table-bordered nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Reference</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Login</th>
                    <th>Mot de passe</th>
                    <th>Fonction</th>
                    <th>Ville</th>
                    <th>Telephone</th>
                    <th>Email</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for commercial in commercials %}
                    <tr>
                        <td>{{ commercial.cKey }}</td>
                        <td>{{ commercial.lastname }}</td>
                        <td>{{ commercial.firstname }}</td>
                        <td>{{ commercial.user.username }}</td>
                        <td><a href="void:javascript(0)">{{ commercial.password|password_hide }}</a></td>
                        <td>{{ commercial.functionName }}</td>
                        <td>{{ commercial.city }}</td>
                        <td>{{ commercial.phone }}</td>
                        <td>{{ commercial.email }}</td>
                        <td>
                            <p data-placement="top" data-toggle="tooltip" title="Delete" style="text-align: center">
                                <button class="btn btn-danger btn-xs delete_commercial" data-title="Delete" data-toggle="modal" data-target="#delete" data-id="{{ commercial.id }}">
                                    <span class="fa fa-trash"></span>
                                </button>
                            </p>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="fa fa-remove" aria-hidden="true"></span></button>
                    <h4 class="modal-title custom_align -align-left" id="Heading">Delete this entry</h4>
                </div>
                <div class="modal-body">

                    <div class="alert alert-danger"><span class="fa fa-exclamation-triangle"></span> Are you sure you want to delete this Record?</div>

                </div>
                <div class="modal-footer ">
                    <button type="button" class="btn btn-success delete_yes" ><span class="fa fa-check"></span> Yes</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><span class="fa fa-times"></span> No</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <script>
        $(document).ready(function() {
            $('#commercials_menu').addClass("active");

            var currentId;
            var table = $('#example').DataTable( {
                "columnDefs": [
                    { "width": "1%", "targets": 0 }
                ],
                "responsive" : true

            } );

            new $.fn.dataTable.FixedHeader( table );
            $("[data-toggle=tooltip]").tooltip();
            $('.delete_commercial').on('click',function(){
                currentId = $(this).data('id');
                $('.delete_yes').trigger('click');
            });
            $('.delete_yes').on('click',function(){
                if(currentId){
                    var url = '{{ path('commercials_remove',{'id' : 'currentId'}) }}';
                    url = url.replace("currentId", currentId);
                    window.location.href = url;
                }
            });
            $('.updater').on('click',function(){
                window.location.href = $(this).data('nextpath');
            });

        } );
    </script>
{% endblock %}